apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    path: 03-platform/cicd/harbor
    repoURL: https://github.com/gymaz/homelab
    targetRevision: develop

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true