 Provider configuration for external secrets to connect to the Vault Backend
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
            name: "vault-token"
            namespace: "default"
            key: "token"
#        kubernetes:
#          mountPath: "auth/kubernetes"
#          role: "grafana"
#          serviceAccountRef:
#            name: "grafana"
#            namespace: "default"