apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-platform-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-apps
    app.kubernetes.io/part-of: platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  
  source:
    repoURL: https://github.com/gymaz/homelab.git
    path: 01-argocd-apps/platform
    targetRevision: develop
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 10
