apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # After Vault is ready
spec:
  provider:
    vault:
      server: "http://vault:8200"
      path: "secret" 
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "default"
          key: "token"
