apiVersion: v2
name: prometheus
description: Prometheus monitoring stack
type: application
version: 1.0.0
dependencies:
  - name: prometheus
    version: "27.32.0"
    repository: https://prometheus-community.github.io/helm-charts
